name: Smart Contract Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]  # Using LTS version of Node

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile

    - name: Run ICO tests
      run: yarn test:ico
      
    - name: Run AMM tests
      run: yarn test:amm

    - name: Run all tests (fallback)
      if: failure()
      run: yarn test